# Generated by Django 3.1 on 2020-09-30 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='', max_length=255)),
                ('quot', models.CharField(default='', max_length=2047)),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
